import { ArrowLeft, ArrowUpRight, Check, UploadCloud } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { saveApplication } from "@/lib/siteContent";
import { appPath, assetPath } from "@/lib/paths";

const logoUrl = assetPath("msec-logo.png");

export default function Tryout() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); saveApplication({ id: crypto.randomUUID(), submittedAt: new Date().toISOString(), name: String(data.get("name") || ""), nickname: String(data.get("nickname") || ""), age: String(data.get("age") || ""), location: String(data.get("location") || ""), game: String(data.get("game") || ""), role: String(data.get("role") || ""), profile: String(data.get("profile") || "") }); setSent(true); };
  return <main className="tryout-shell"><nav className="story-nav"><Link href={appPath("/")}><ArrowLeft size={15} /> Voltar ao site</Link><div className="story-brand"><img src={logoUrl} alt="MSEC — Me Sinto em Casa" /><span>MSEC <em>TRYOUT</em></span></div><Link href={appPath("/story")}>Nossa história <ArrowUpRight size={15} /></Link></nav><section className="tryout-layout"><div className="tryout-intro"><span className="section-kicker">MSEC / RECRUTAMENTO</span><h1>Entra na<br /><span>matilha.</span></h1><p>Tem mira, voz, vontade ou uma história boa? Conta pra gente. A MSEC está sempre procurando quem quer construir algo junto.</p><div className="tryout-note"><img src={logoUrl} alt="" /><span>Me Sinto em Casa é para quem chega e sente que encontrou seu lugar.</span></div></div><form className="tryout-form" onSubmit={submit}><div className="form-top"><span>01 / SUA FICHA</span><span>LEVA 2 MIN</span></div>{sent ? <div className="form-success"><Check size={28} /><h2>Ficha recebida.</h2><p>Valeu por chegar junto. A matilha vai olhar seu perfil e entrar em contato.</p><Link className="button button-primary" href={appPath("/")}>Voltar ao site <ArrowUpRight size={16} /></Link></div> : <><div className="tryout-fields"><label>Nome completo<input required name="name" placeholder="Como podemos te chamar?" /></label><label>Nickname<input required name="nickname" placeholder="Seu nick nas partidas" /></label><label>Idade<input required type="number" min="13" name="age" placeholder="18" /></label><label>Cidade / estado<input required name="location" placeholder="São Paulo, SP" /></label><label>Jogo principal<select required name="game" defaultValue=""><option value="" disabled>Escolha uma modalidade</option><option>EA FC</option><option>Valorant</option><option>Rocket League</option><option>Outro</option></select></label><label>Função<input required name="role" placeholder="Ex.: atacante, duelista, suporte" /></label><label className="full">Link de perfil ou clipes<input name="profile" placeholder="Twitch, YouTube, Tracker, etc." /></label><label className="full upload-label"><UploadCloud size={16} /> Clipe ou apresentação (opcional)<input type="file" accept="video/*,.pdf,.doc,.docx" /></label></div><button className="button button-primary tryout-submit" type="submit">Enviar minha ficha <ArrowUpRight size={16} /></button><small>Ao enviar, você concorda que a MSEC entre em contato sobre o processo seletivo.</small></>}</form></section></main>;
}
